[theme]
primaryColor = "#C3979F"
backgroundColor = "#CCDDB7"
secondaryBackgroundColor = "#545775"
textColor = "#34252f"
font = "serif"

[general]
pageTitle = "Care Connect"
pageIcon = "🤝"

[server]
layout = "center"
initialSidebarState = "auto"
