[theme]
primaryColor = "#C3979F"
backgroundColor = "#98C1D9"
secondaryBackgroundColor = "#023C40"
textColor = "#333333"
font = "serif"

[general]
pageTitle = "Care Connect"
pageIcon = "🤝"

[server]
layout = "center"
initialSidebarState = "auto"
