[theme]
primaryColor = "#C3979F"
backgroundColor = "#3B5249"
secondaryBackgroundColor = "#D5A18E"
textColor = "#34252f"
font = "serif"

[general]
pageTitle = "Care Connect"
pageIcon = "🤝"

[server]
layout = "center"
initialSidebarState = "auto"
