[theme]
primaryColor = "#C3979F"
backgroundColor = "#98C1D9"
secondaryBackgroundColor = "#C3979F"
textColor = "#080808"
font = "serif"

[general]
pageTitle = "Care Connect"
pageIcon = "🤝"

[server]
layout = "center"
initialSidebarState = "auto"
